FROM node:8-alpine

RUN mkdir -p /opt/app

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

ARG PORT=4200
ENV PORT $PORT
EXPOSE $PORT 9229 9230

RUN npm i npm@latest -g

WORKDIR /opt
COPY ./app/package.json ./app/package-lock.json* ./
RUN npm install && npm cache clean --force

WORKDIR /opt/app
COPY ./dist/ /opt/app
COPY ./app/server.js /opt/app

CMD [ "npm", "start" ]