version: '3.1'

services:
  node-server:
    container_name: backend
    build:
      context: ./server/
      args:
        - NODE_ENV=development
    command: npm run dev
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/opt/app:delegated
      - ./server/package.json:/opt/package.json
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    restart: on-failure
    depends_on:
      - mongo
    links:
      - mongo

  node-client:
    container_name: frontend
    build:
      context: ./client/
      args:
        - NODE_ENV=development
    command: npm run dev
    ports:
      - "4200:4200"
    volumes:
      - ./client/:/opt/app:delegated
      - ./client/package.json:/opt/package.json
      - notused2:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    links:
      - node-server
      
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./database/:/data/db
volumes:
    notused:
    notused2: